set(_CATKIN_CURRENT_PACKAGE "autofocus")
set(autofocus_VERSION "0.0.0")
set(autofocus_MAINTAINER "jonathanfascetti <jonathanfascetti@todo.todo>")
set(autofocus_PACKAGE_FORMAT "2")
set(autofocus_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(autofocus_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(autofocus_BUILDTOOL_DEPENDS "catkin")
set(autofocus_BUILDTOOL_EXPORT_DEPENDS )
set(autofocus_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(autofocus_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(autofocus_TEST_DEPENDS )
set(autofocus_DOC_DEPENDS )
set(autofocus_URL_WEBSITE "")
set(autofocus_URL_BUGTRACKER "")
set(autofocus_URL_REPOSITORY "")
set(autofocus_DEPRECATED "")