# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# compile C with /usr/bin/cc
# compile CXX with /usr/bin/c++
C_FLAGS = -fPIC  

C_DEFINES = -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"imu_vn_100\" -Dimu_vn_100_EXPORTS

C_INCLUDES = -I/home/jonathanfascetti/catkin_ws/src/imu_vn_100/include -I/home/jonathanfascetti/catkin_ws/src/imu_vn_100/vncpplib/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp 

CXX_FLAGS =  -std=c++11 -Wall -fPIC  

CXX_DEFINES = -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"imu_vn_100\" -Dimu_vn_100_EXPORTS

CXX_INCLUDES = -I/home/jonathanfascetti/catkin_ws/src/imu_vn_100/include -I/home/jonathanfascetti/catkin_ws/src/imu_vn_100/vncpplib/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp 

