set(_CATKIN_CURRENT_PACKAGE "jon_pack")
set(jon_pack_VERSION "0.0.0")
set(jon_pack_MAINTAINER "jonathanfascetti <jonathanfascetti@todo.todo>")
set(jon_pack_PACKAGE_FORMAT "2")
set(jon_pack_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(jon_pack_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(jon_pack_BUILDTOOL_DEPENDS "catkin")
set(jon_pack_BUILDTOOL_EXPORT_DEPENDS )
set(jon_pack_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(jon_pack_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(jon_pack_TEST_DEPENDS )
set(jon_pack_DOC_DEPENDS )
set(jon_pack_URL_WEBSITE "")
set(jon_pack_URL_BUGTRACKER "")
set(jon_pack_URL_REPOSITORY "")
set(jon_pack_DEPRECATED "")